export interface Bono {
  Nombre: any,
  MValorNominal: any,
  MValorComercial: any,
  QAniosPago: any,
  NPeriodoFrecuenciaCuponTipo: any,
  QDias: any,
  TipoTasaIsEfectiva: any,
  NPeriodoCapitalTNTipo: any,
  PerTasaInteres: any,
  PerTasaAnualDescuento: any,
  PerImportRenta: any,
  DEmision: any,
  PerPrima: any,
  PerEstructuracion: any,
  PerColocacion: any,
  PerFlotacion: any,
  PerCavali: any,
  QPeriodosGracia: any,
  LInflacionAnual: any
}
